config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups

  resources :teachers

  resources :students

  root 'application#overview'

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :code, presence: true, uniqueness: true

  belongs_to :teacher
  has_and_belongs_to_many :students, uniq: true

  self.inheritance_column = nil
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  validates :code, uniqueness: true
  self.per_page = 100

  has_attached_file :picture, :styles => {
    :thumb => "100x140>"
  }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  has_and_belongs_to_many :groups, uniq: true

  def full_name
    [name, infix, surname].reject(&:blank?).join(' ')
  end

  def associate_group(group)
    self.groups << group unless self.groups.include?(group)
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :groups
  has_many :students, through: :groups

  def full_name
    [name, infix, surname].reject(&:blank?).join(' ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def overview
    @groups = Group.all
    if params[:group_id]
      @students = Group.find_by_id(params[:group_id]).students
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params[:group]
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.paginate(:page => params[:page])
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:code, :name, :infix, :surname, :picture)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params[:teacher]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/application/_students.html.erb
<% @students.each.with_index do |student, index| %>
  <% if index == 0 %><div class="row small-gutter"><% end %>
    <div class="col-xs-3 student">
      <div class="thumbnail">
        <%= image_tag student.picture.url(:thumb) %>
        <div class="caption">
          <small><%= link_to student.name, student_path(student) %></small>
        </div>
      </div>
    </div>
  <% if (index + 1).modulo(6).zero? || (index + 1) == @students.each.count %>
    </div>
    <%= raw('<div class="row small-gutter">') unless (index + 1) == @students.each.count %>
  <% end %>
<% end %>

app/views/application/overview.html.erb
<div class="row">
  <div class="col-xs-6">
    <strong>Klas</strong>
    <div class="pull-right">
      <select onchange="changeGroup(event)">
        <option>Kies een klas...</option>
        <optgroup label="Klassen">
          <% @groups.where(type: nil).order(code: :asc).each do |group| %>
            <option value="<%= group.id %>" <%= 'selected' if group.id == params[:group_id].to_i %>>
              <%= group.code %>
            </option>
          <% end %>
        </optgroup>
        <optgroup label="Clusters">
          <% @groups.where.not(type: nil).order(code: :asc).each do |group| %>
            <option value="<%= group.id %>" <%= 'selected' if group.id == params[:group_id].to_i %>>
              <%= group.code %>
            </option>
          <% end %>
        </optgroup>
      </select>
    </div>
    <hr>

    <% if @students %>
      <%= render "students" %>
    <% else %>
      Welkom
    <% end %>
  </div>
  <div class="col-xs-6">
    <strong>Computers</strong>
    <hr>
    <div class="row small-gutter">
      <% (1..10).each do %>
        <div class="col-xs-3 computer">
          <a href="#" class="thumbnail">
            <img data-src="holder.js/100%x110" alt="...">
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_students.html.erb
<% @group.students.each.with_index do |student, index| %>
  <% if index == 0 %><div class="row small-gutter"><% end %>
    <div class="col-xs-2">
      <a href="<%= student_path(student) %>" class="thumbnail">
        <%= image_tag student.picture.url(:thumb) %>
        <div class="caption">
          <small><%= student.full_name %></small>
        </div>
      </a>
    </div>
  <% if (index + 1).modulo(5).zero? || (index + 1) == @group.students.each.count %>
    </div>
    <%= raw('<div class="row small-gutter">') unless (index + 1) == @group.students.each.count %>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups (<%= @groups.count %>)</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Type</th>
      <th>Teacher</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.code %></td>
        <td><%= group.type %></td>
        <td><%= group.teacher.full_name if group.teacher %></td>
        <td><%= group.students.count %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1><%= @group.code %></h1>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to 'Back', groups_path, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-primary' %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-6 col-sm-12">
      <%= render 'students' %>
  </div>
  <div class="col-md-6">
    <div class="well">
      <p>
      <strong>Mentor:</strong>
      <% if @group.teacher %>
        <%= link_to("#{@group.teacher.full_name} (#{@group.teacher.code})", teacher_path(@group.teacher)) %>
      <% else %>
        <span class="text-muted">geen</span>
      <% end %>
      </p>
      <p><%= @group.students.count %> leerlingen</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medreg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <a class="navbar-brand" href="/">MedReg</a>
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'application' %>">
        <%= link_to 'Overview', :root %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'groups' %>">
        <%= link_to 'Groups', :groups %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'teachers' %>">
        <%= link_to 'Teachers', :teachers %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'students' %>">
        <%= link_to 'Students', :students %>
      </li>
    </ul>
    <p class="navbar-text navbar-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>
</nav>

<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/students/_form.html.erb
<%= bootstrap_form_for(@student, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", html: { multipart: true }) do |f| %>
  <% if @student.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</strong>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :picture %>
    <%= f.text_field :code %>
    <%= f.text_field :name %>
    <%= f.text_field :infix %>
    <%= f.text_field :surname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Students</h1>
    <p class="text-muted">Students: <%= @students.count %></p>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to 'New Student', new_student_path, class: 'btn btn-primary' %>
  </div>
</div>

<hr>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.code %></td>
      <td><%= student.full_name %></td>
      <td><%= link_to 'Show', student %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1><%= @student.full_name %></h1>
    <p><%= @student.code %> &mdash;
    <% first_group = @student.groups.first %>
    <% if first_group %>
      <%= link_to first_group.code, group_path(first_group) %>
      <% if first_group.teacher %>
        &mdash;
        <%= link_to "#{first_group.teacher.full_name} (#{first_group.teacher.code})", teacher_path(first_group.teacher) %>
      <% end %>
    <% end %>
    </p>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to 'Back', students_path, class: 'btn btn-default' %>
    <%= link_to 'Edit Student', edit_student_path(@student), class: 'btn btn-primary' %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-2">
    <%= image_tag @student.picture.url(:thumb) %>
  </div>
  <div class="col-xs-10">
    <strong>Klassen en clusters:</strong>
    <ul>
      <% @student.groups.each do |group| %>
        <li><%= link_to group.code, group_path(group) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Teachers</h1>
    <p class="text-muted">Teachers: <%= @teachers.count %></p>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to 'New Teacher', new_teacher_path, class: 'btn btn-primary' %>
  </div>
</div>

<hr>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Groups</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.code %></td>
        <td><%= teacher.full_name %></td>
        <td><%= teacher.groups.count %></td>
        <td><%= teacher.students.count %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<h1><%= @teacher.full_name %> (<%= @teacher.code %>)</h1>

<div class="row">
  <div class="col-xs-6">
    <%= link_to 'Edit', edit_teacher_path(@teacher) %> |
    <%= link_to 'Back', teachers_path %>
  </div>
  <div class="col-xs-6 text-right">

  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-2">
    <% if @teacher.groups.count > 0 %>
      <strong>Mentorklassen:</strong>
    <% end %>
    <ul>
      <% @teacher.groups.each do |group| %>
        <li><%= link_to group.code, group_path(group) %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-10">

  </div>
</div>